import type { Task, Category } from "./types"

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Complete project documentation",
    description: "Write comprehensive documentation for the new feature",
    completed: false,
    priority: "high",
    category: "Work",
    dueDate: new Date(2025, 0, 15),
    createdAt: new Date(2025, 0, 10),
    tags: ["documentation", "urgent"],
    subtasks: [
      { id: "s1", title: "API documentation", completed: true },
      { id: "s2", title: "User guide", completed: false },
      { id: "s3", title: "Examples", completed: false },
    ],
  },
  {
    id: "2",
    title: "Review pull requests",
    completed: false,
    priority: "medium",
    category: "Work",
    dueDate: new Date(2025, 0, 14),
    createdAt: new Date(2025, 0, 12),
    tags: ["code-review"],
    subtasks: [],
  },
  {
    id: "3",
    title: "Grocery shopping",
    description: "Buy ingredients for dinner party",
    completed: false,
    priority: "medium",
    category: "Personal",
    dueDate: new Date(2025, 0, 13),
    createdAt: new Date(2025, 0, 11),
    tags: ["shopping", "errands"],
    subtasks: [],
  },
  {
    id: "4",
    title: "Team meeting preparation",
    completed: true,
    priority: "high",
    category: "Work",
    dueDate: new Date(2025, 0, 12),
    createdAt: new Date(2025, 0, 8),
    tags: ["meeting"],
    subtasks: [],
  },
  {
    id: "5",
    title: 'Read "Atomic Habits"',
    completed: false,
    priority: "low",
    category: "Learning",
    tags: ["books", "self-improvement"],
    createdAt: new Date(2025, 0, 5),
    subtasks: [],
  },
  {
    id: "6",
    title: "Update portfolio website",
    description: "Add recent projects and update design",
    completed: false,
    priority: "medium",
    category: "Personal",
    dueDate: new Date(2025, 0, 20),
    createdAt: new Date(2025, 0, 9),
    tags: ["web-dev", "portfolio"],
    subtasks: [],
  },
  {
    id: "7",
    title: "Fitness routine",
    completed: true,
    priority: "medium",
    category: "Health",
    dueDate: new Date(2025, 0, 12),
    createdAt: new Date(2025, 0, 12),
    tags: ["exercise", "health"],
    subtasks: [],
  },
  {
    id: "8",
    title: "Learn React Server Components",
    description: "Complete tutorial series on RSC",
    completed: false,
    priority: "high",
    category: "Learning",
    dueDate: new Date(2025, 0, 18),
    createdAt: new Date(2025, 0, 7),
    tags: ["react", "learning", "web-dev"],
    subtasks: [],
  },
]

export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Work",
    color: "oklch(0.7 0.2 260)",
    icon: "Briefcase",
    taskCount: 3,
  },
  {
    id: "2",
    name: "Personal",
    color: "oklch(0.6 0.15 180)",
    icon: "User",
    taskCount: 2,
  },
  {
    id: "3",
    name: "Learning",
    color: "oklch(0.65 0.18 340)",
    icon: "BookOpen",
    taskCount: 2,
  },
  {
    id: "4",
    name: "Health",
    color: "oklch(0.55 0.12 120)",
    icon: "Heart",
    taskCount: 1,
  },
]
