export const EDITOR_CONFIG = {
  minFontSize: 8,
  maxFontSize: 32,
  defaultFontSize: 14,
  fontSizeStep: 2,

  minTabSize: 2,
  maxTabSize: 8,
  defaultTabSize: 4,

  maxHistoryEntries: 50,
  autoSaveInterval: 30000, // 30 seconds

  supportedFileExtensions: [
    ".txt",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".html",
    ".css",
    ".scss",
    ".json",
    ".md",
    ".py",
    ".java",
    ".cpp",
    ".c",
    ".cs",
    ".php",
    ".rb",
    ".go",
    ".rs",
    ".swift",
    ".kt",
    ".sql",
    ".sh",
    ".xml",
    ".yaml",
    ".yml",
  ],
}

export const KEYBOARD_SHORTCUTS = {
  newFile: "Ctrl+N",
  openFile: "Ctrl+O",
  saveFile: "Ctrl+S",
  saveFileAs: "Ctrl+Shift+S",
  newTab: "Ctrl+T",
  closeTab: "Ctrl+W",
  find: "Ctrl+F",
  replace: "Ctrl+H",
  settings: "Ctrl+,",
  undo: "Ctrl+Z",
  redo: "Ctrl+Y",
  cut: "Ctrl+X",
  copy: "Ctrl+C",
  paste: "Ctrl+V",
  selectAll: "Ctrl+A",
  zoomIn: "Ctrl++",
  zoomOut: "Ctrl+-",
  resetZoom: "Ctrl+0",
}
